export class ProductDetail {
  id?: number;
  // tslint:disable-next-line:variable-name
  producer_address_id?: number;
  name?: string;
  slug?: string;
  // tslint:disable-next-line:variable-name
  parent_name?: string;
  // tslint:disable-next-line:variable-name
  producer_name?: string;
  // tslint:disable-next-line:variable-name
  producer_type_name?: string;
  // tslint:disable-next-line:variable-name
  city_name?: string;
  // tslint:disable-next-line:variable-name
  district_name?: string;
  // tslint:disable-next-line:variable-name
  // tslint:disable-next-line:variable-name
  category_name?: string;
  // tslint:disable-next-line:variable-name
  production_type?: string;
  // tslint:disable-next-line:variable-name
  detailed_name?: string;
  price?: string;
  photo?: string;
  // tslint:disable-next-line:variable-name
  harvest_start?: string;
  // tslint:disable-next-line:variable-name
  harvest_end?: string;
  // tslint:disable-next-line:variable-name
  total_amount?: string;
  // tslint:disable-next-line:variable-name
  total_amount_quantity?: string;
  // tslint:disable-next-line:variable-name
  square_meter?: string;
  // tslint:disable-next-line:variable-name
  square_meter_unit?: string;
  // tslint:disable-next-line:variable-name
  created_at?: string;
  // tslint:disable-next-line:variable-name
  city_name_slug?: string;
  // tslint:disable-next-line:variable-name
  detailed_name_slug?: string;
  // tslint:disable-next-line:variable-name
  path?: string;
}
